from datetime import datetime
from typing import Literal
from pydantic import BaseModel, Field


class PaymentRequest(BaseModel):
    card_number: str = Field(
        min_length=14, max_length=19, pattern=r'^[0-9]+$',
        description="14-19 characters, numbers only"
    )
    card_expiration_month: str = Field(
        min_length=1, max_length=2, pattern=r'^[0-9]+$',
        description="1-12"
    )
    card_expiration_year: str = Field(
        min_length=4, max_length=4, pattern=r'^[0-9]+$',
        description="Must be in the future (with month)"
    )
    card_cvv: str = Field(
        min_length=3, max_length=4, pattern=r'^[0-9]+$',
        description="3-4 characters, numbers only"
    )
    currency: str = Field(
        min_length=3, max_length=3, pattern=r'^[A-Z]+$',
        description="3 characters, ISO currency code (e.g. GBP, USD)"
    )
    amount: str = Field(
        description="Amount in cents, $0.01 would be supplied as 1"
    )

class PaymentResponse(BaseModel):
    payment_id: str = Field(
        description="Payment ID generated by the payment gateway"
    )
    status: Literal["Authorized", "Declined", "Rejected"] = Field(description="Authorized | Declined | Rejected")
    card_last_four: str = Field(
        min_length=4, max_length=4, pattern=r'^[0-9]+$',
        description="Last 4 digits of the card number"
    )
    card_expiration_month: str = Field(
        min_length=1, max_length=2, pattern=r'^[0-9]+$',
        description="1-12"
    )
    card_expiration_year: str = Field(
        min_length=4, max_length=4, pattern=r'^[0-9]+$', 
        description="Must be in the future (with month)"
    )
    currency: str = Field(
        min_length=3, max_length=3, pattern=r'^[A-Z]+$',
        description="3 characters, ISO currency code"
    )
    amount: str = Field(
        description="Amount in cents, $0.01 would be supplied as 1"
    )

class PaymentRequestValidator:
    @staticmethod
    def validate_card_number(card_number: str) -> bool:
        import re
        if len(card_number) < 14 or len(card_number) > 19:
            return False
        if not re.match(r'^[0-9]+$', card_number):
            return False
        return True

    @staticmethod
    def validate_card_expiration_month(card_expiration_month: str) -> bool:
        return int(card_expiration_month) >= 1 and int(card_expiration_month) <= 12
    
    @staticmethod
    def validate_card_expiration_year(card_expiration_year: str) -> bool:
        return int(card_expiration_year) >= datetime.now().year
    
    @staticmethod
    def validate_card_expiration_date(card_expiration_month: str, card_expiration_year: str) -> bool:
        if int(card_expiration_year) < datetime.now().year:
            return False
        if int(card_expiration_year) == datetime.now().year and int(card_expiration_month) < datetime.now().month:
            return False
        return True
    
    @staticmethod
    def validate_currency(currency: str) -> bool:
        import pycountry
        return pycountry.currencies.get(alpha_3=currency) is not None
    
    @staticmethod
    def validate_amount(amount: str) -> bool:
        return int(amount) >= 1
    
    @staticmethod
    def validate_payment_request(payment_request: PaymentRequest) -> bool:
        if not PaymentRequestValidator.validate_card_number(payment_request.card_number):
            return False
        if not PaymentRequestValidator.validate_card_expiration_month(payment_request.card_expiration_month):
            return False
        if not PaymentRequestValidator.validate_card_expiration_year(payment_request.card_expiration_year):
            return False
        if not PaymentRequestValidator.validate_card_expiration_date(payment_request.card_expiration_month, payment_request.card_expiration_year):
            return False
        if not PaymentRequestValidator.validate_currency(payment_request.currency):
            return False
        if not PaymentRequestValidator.validate_amount(payment_request.amount):
            return False
        return True
